wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
dataset:
  value: mnist
epochs:
  value: 10
hidden_layers:
  value: 1
learning_rate:
  value: 0.0018177049283937385
loss:
  value: cross_entropy
num_neurons:
  value: 32
optimizer:
  value: adam
weight_init:
  value: xavier
