wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_layers:
  value: 4
learning_rate:
  value: 0.0007054167948321823
loss:
  value: cross_entropy
num_neurons:
  value: 128
optimizer:
  value: nadam
weight_init:
  value: random
