wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 10
hidden_layers:
  value: 1
learning_rate:
  value: 0.0032751927763287935
loss:
  value: cross_entropy
num_neurons:
  value: 32
optimizer:
  value: nadam
weight_init:
  value: xavier
