wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
l1_size:
  value: 128
l2_size:
  value: 32
l3_size:
  value: 64
l4_size:
  value: 64
l5_size:
  value: 32
l6_size:
  value: 64
learning_rate:
  value: 0.021561072017490274
loss:
  value: mse
num_layers:
  value: 6
optimizer:
  value: momentum
weight_init:
  value: xavier
