wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
l1_size:
  value: 32
l2_size:
  value: 128
l3_size:
  value: 128
l4_size:
  value: 128
l5_size:
  value: 64
l6_size:
  value: 32
learning_rate:
  value: 0.009514065575724168
loss:
  value: mse
num_layers:
  value: 5
optimizer:
  value: momentum
weight_init:
  value: random
