wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
l1_size:
  value: 128
l2_size:
  value: 32
l3_size:
  value: 128
l4_size:
  value: 128
l5_size:
  value: 128
l6_size:
  value: 128
learning_rate:
  value: 0.00014785257621760612
loss:
  value: mse
num_layers:
  value: 5
optimizer:
  value: sgd
weight_init:
  value: xavier
