wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
l1_size:
  value: 32
l2_size:
  value: 64
l3_size:
  value: 64
l4_size:
  value: 128
l5_size:
  value: 64
l6_size:
  value: 32
learning_rate:
  value: 0.0001183878723190416
loss:
  value: mse
num_layers:
  value: 3
optimizer:
  value: rmsprop
weight_init:
  value: random
