wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
l1_size:
  value: 64
l2_size:
  value: 64
l3_size:
  value: 64
l4_size:
  value: 128
l5_size:
  value: 32
l6_size:
  value: 64
learning_rate:
  value: 0.019977137239359535
loss:
  value: mse
num_layers:
  value: 6
optimizer:
  value: rmsprop
weight_init:
  value: random
