wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
l1_size:
  value: 64
l2_size:
  value: 128
l3_size:
  value: 32
l4_size:
  value: 64
l5_size:
  value: 64
l6_size:
  value: 32
learning_rate:
  value: 0.07012100564704349
loss:
  value: mse
num_layers:
  value: 4
optimizer:
  value: momentum
weight_init:
  value: xavier
