wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
l1_size:
  value: 128
l2_size:
  value: 32
l3_size:
  value: 128
l4_size:
  value: 32
l5_size:
  value: 64
l6_size:
  value: 128
learning_rate:
  value: 0.0020509468722549797
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: sgd
weight_init:
  value: random
