wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
l1_size:
  value: 64
l2_size:
  value: 128
l3_size:
  value: 128
l4_size:
  value: 64
l5_size:
  value: 128
l6_size:
  value: 32
learning_rate:
  value: 0.038062581675111985
loss:
  value: cross_entropy
num_layers:
  value: 6
optimizer:
  value: rmsprop
weight_init:
  value: xavier
