wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
l1_size:
  value: 32
l2_size:
  value: 64
l3_size:
  value: 64
l4_size:
  value: 128
l5_size:
  value: 32
l6_size:
  value: 32
learning_rate:
  value: 0.001701777390370319
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: sgd
weight_init:
  value: random
