wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
l1_size:
  value: 64
l2_size:
  value: 128
l3_size:
  value: 32
l4_size:
  value: 64
l5_size:
  value: 64
l6_size:
  value: 128
learning_rate:
  value: 0.0006995003207775804
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: nag
weight_init:
  value: random
