wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
l1_size:
  value: 32
l2_size:
  value: 64
l3_size:
  value: 128
l4_size:
  value: 32
l5_size:
  value: 32
l6_size:
  value: 64
learning_rate:
  value: 0.001235388208782903
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: rmsprop
weight_init:
  value: xavier
