wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
l1_size:
  value: 128
l2_size:
  value: 64
l3_size:
  value: 64
l4_size:
  value: 128
l5_size:
  value: 128
l6_size:
  value: 32
learning_rate:
  value: 0.0048125698304520865
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: momentum
weight_init:
  value: random
