wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
l1_size:
  value: 64
l2_size:
  value: 64
l3_size:
  value: 128
l4_size:
  value: 128
l5_size:
  value: 128
l6_size:
  value: 64
learning_rate:
  value: 0.00017662228162300265
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: nag
weight_init:
  value: xavier
