wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
l1_size:
  value: 32
l2_size:
  value: 32
l3_size:
  value: 128
l4_size:
  value: 32
l5_size:
  value: 32
l6_size:
  value: 64
learning_rate:
  value: 0.014671507126941211
loss:
  value: mse
num_layers:
  value: 3
optimizer:
  value: sgd
weight_init:
  value: xavier
