wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
l1_size:
  value: 32
l2_size:
  value: 32
l3_size:
  value: 128
l4_size:
  value: 128
l5_size:
  value: 64
l6_size:
  value: 128
learning_rate:
  value: 0.04762080873325309
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: nag
weight_init:
  value: xavier
