wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
l1_size:
  value: 32
l2_size:
  value: 32
l3_size:
  value: 64
l4_size:
  value: 32
l5_size:
  value: 32
l6_size:
  value: 32
learning_rate:
  value: 0.006771543936482507
loss:
  value: mse
num_layers:
  value: 5
optimizer:
  value: nag
weight_init:
  value: xavier
