wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
l1_size:
  value: 32
l2_size:
  value: 32
l3_size:
  value: 64
l4_size:
  value: 32
l5_size:
  value: 128
l6_size:
  value: 32
learning_rate:
  value: 0.000337657511507997
loss:
  value: cross_entropy
num_layers:
  value: 3
optimizer:
  value: rmsprop
weight_init:
  value: random
