wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
l1_size:
  value: 128
l2_size:
  value: 32
l3_size:
  value: 128
l4_size:
  value: 32
l5_size:
  value: 64
l6_size:
  value: 64
learning_rate:
  value: 0.008099457506921322
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: nag
weight_init:
  value: xavier
