wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
l1_size:
  value: 32
l2_size:
  value: 32
l3_size:
  value: 32
l4_size:
  value: 128
l5_size:
  value: 64
l6_size:
  value: 128
learning_rate:
  value: 0.00012379168940678274
loss:
  value: mse
num_layers:
  value: 6
optimizer:
  value: nag
weight_init:
  value: xavier
