wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
l1_size:
  value: 64
l2_size:
  value: 32
l3_size:
  value: 128
l4_size:
  value: 128
l5_size:
  value: 64
l6_size:
  value: 64
learning_rate:
  value: 0.001661591114799647
loss:
  value: mse
num_layers:
  value: 6
optimizer:
  value: nag
weight_init:
  value: random
