wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
hidden_size:
  value: 64
learning_rate:
  value: 0.042130868525436835
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: momentum
weight_init:
  value: random
