wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
hidden_size:
  value: 64
learning_rate:
  value: 0.0002876223883049812
loss:
  value: mse
num_layers:
  value: 5
optimizer:
  value: rmsprop
weight_init:
  value: random
