wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
hidden_size:
  value: 128
learning_rate:
  value: 0.04761779953518599
loss:
  value: mse
num_layers:
  value: 4
optimizer:
  value: rmsprop
weight_init:
  value: xavier
