wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
hidden_size:
  value: 128
learning_rate:
  value: 0.00014748168116506804
loss:
  value: mse
num_layers:
  value: 6
optimizer:
  value: momentum
weight_init:
  value: random
