wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
hidden_size:
  value: 64
learning_rate:
  value: 0.0008895935033454616
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: momentum
weight_init:
  value: random
