wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
hidden_size:
  value: 64
learning_rate:
  value: 0.0005358331177241254
loss:
  value: mse
num_layers:
  value: 4
optimizer:
  value: nag
weight_init:
  value: xavier
