wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
hidden_size:
  value: 128
learning_rate:
  value: 0.00016601795458283264
loss:
  value: mse
num_layers:
  value: 3
optimizer:
  value: momentum
weight_init:
  value: xavier
