wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
hidden_size:
  value: 64
learning_rate:
  value: 0.006377125018771774
loss:
  value: mse
num_layers:
  value: 4
optimizer:
  value: sgd
weight_init:
  value: xavier
