wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
hidden_size:
  value: 64
learning_rate:
  value: 0.024789687114759592
loss:
  value: mse
num_layers:
  value: 2
optimizer:
  value: rmsprop
weight_init:
  value: xavier
