wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
hidden_size:
  value: 32
learning_rate:
  value: 0.00024054426683920937
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: nag
weight_init:
  value: xavier
