wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
hidden_size:
  value: 32
learning_rate:
  value: 0.02586809090421605
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: sgd
weight_init:
  value: xavier
