wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
hidden_size:
  value: 32
learning_rate:
  value: 0.001918332922887942
loss:
  value: mse
num_layers:
  value: 3
optimizer:
  value: nag
weight_init:
  value: random
