wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
hidden_size:
  value: 32
learning_rate:
  value: 0.0021918235561944302
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: nag
weight_init:
  value: random
