wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
hidden_size:
  value: 64
learning_rate:
  value: 0.06758118371872962
loss:
  value: mse
num_layers:
  value: 6
optimizer:
  value: rmsprop
weight_init:
  value: xavier
