wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
hidden_size:
  value: 32
learning_rate:
  value: 0.0001628653157309514
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: rmsprop
weight_init:
  value: random
