wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
hidden_size:
  value: 64
learning_rate:
  value: 0.00010935184456923896
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: sgd
weight_init:
  value: random
