wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
hidden_size:
  value: 64
learning_rate:
  value: 0.005885653952520324
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: rmsprop
weight_init:
  value: xavier
