wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
hidden_size:
  value: 32
learning_rate:
  value: 0.017217753602855518
loss:
  value: mse
num_layers:
  value: 6
optimizer:
  value: sgd
weight_init:
  value: xavier
