wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
hidden_size:
  value: 32
learning_rate:
  value: 0.006426474059372143
loss:
  value: mse
num_layers:
  value: 6
optimizer:
  value: nag
weight_init:
  value: random
