wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
hidden_size:
  value: 128
learning_rate:
  value: 0.00014543505828632126
loss:
  value: mse
num_layers:
  value: 3
optimizer:
  value: sgd
weight_init:
  value: random
