wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
hidden_size:
  value: 32
learning_rate:
  value: 0.009655110997513944
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: momentum
weight_init:
  value: random
