wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
hidden_size:
  value: 64
learning_rate:
  value: 0.0002702893003803868
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: sgd
weight_init:
  value: random
