wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
hidden_size:
  value: 32
learning_rate:
  value: 0.07877035994964922
loss:
  value: cross_entropy
num_layers:
  value: 2
optimizer:
  value: momentum
weight_init:
  value: xavier
