wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
hidden_size:
  value: 32
learning_rate:
  value: 0.02195584648591598
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: nag
weight_init:
  value: xavier
