wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
hidden_size:
  value: 32
learning_rate:
  value: 0.021703938928844504
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: momentum
weight_init:
  value: xavier
