wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
hidden_size:
  value: 64
learning_rate:
  value: 0.009109489476197963
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: sgd
weight_init:
  value: random
