wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
hidden_size:
  value: 64
learning_rate:
  value: 0.00011543870535032452
loss:
  value: mse
num_layers:
  value: 5
optimizer:
  value: rmsprop
weight_init:
  value: xavier
