wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
hidden_size:
  value: 32
learning_rate:
  value: 0.011121836232093826
loss:
  value: mse
num_layers:
  value: 5
optimizer:
  value: rmsprop
weight_init:
  value: xavier
