wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
hidden_size:
  value: 64
learning_rate:
  value: 0.00018604542666947197
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: sgd
weight_init:
  value: xavier
