wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
hidden_size:
  value: 32
learning_rate:
  value: 0.01485507609735049
loss:
  value: mse
num_layers:
  value: 5
optimizer:
  value: sgd
weight_init:
  value: random
