wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
hidden_size:
  value: 128
learning_rate:
  value: 0.0019640627595121215
loss:
  value: cross_entropy
num_layers:
  value: 4
optimizer:
  value: rmsprop
weight_init:
  value: xavier
