wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
hidden_size:
  value: 128
learning_rate:
  value: 0.00016436249701521225
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: rmsprop
weight_init:
  value: random
