wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
hidden_size:
  value: 32
learning_rate:
  value: 0.02245665720176455
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: momentum
weight_init:
  value: xavier
