wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
hidden_size:
  value: 64
learning_rate:
  value: 0.0003689675412783302
loss:
  value: mse
num_layers:
  value: 5
optimizer:
  value: sgd
weight_init:
  value: xavier
