wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
hidden_size:
  value: 64
learning_rate:
  value: 0.00026412451722443187
loss:
  value: mse
num_layers:
  value: 6
optimizer:
  value: sgd
weight_init:
  value: random
