wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
hidden_size:
  value: 128
learning_rate:
  value: 0.004131384676953531
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: rmsprop
weight_init:
  value: random
