wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
hidden_size:
  value: 128
learning_rate:
  value: 0.04917358174530826
loss:
  value: mse
num_layers:
  value: 5
optimizer:
  value: momentum
weight_init:
  value: xavier
