wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
hidden_size:
  value: 128
learning_rate:
  value: 0.024614089277551616
loss:
  value: cross_entropy
num_layers:
  value: 6
optimizer:
  value: rmsprop
weight_init:
  value: random
