wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
hidden_size:
  value: 64
learning_rate:
  value: 0.036813523789013536
loss:
  value: cross_entropy
num_layers:
  value: 5
optimizer:
  value: rmsprop
weight_init:
  value: random
