_wandb:
    value:
        cli_version: 0.25.0
        e:
            1huk4rwjfp6yyqov9ehxxvrd6da7btgd:
                codePath: src/weight_init_symmetry.py
                codePathLocal: src/weight_init_symmetry.py
                email: kowshikisme@gmail.com
                executable: /home/kowshik/miniconda3/bin/python
                git:
                    commit: 7c1f401865dc249c39e48c9e3d1afa6c313b6b4f
                    remote: https://github.com/ItsKowshik/DA6401_Assignment1.git
                host: ItsKowshik07
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: /home/kowshik/Old_G/Semester_2/DL/Assignment_1/src/weight_init_symmetry.py
                python: CPython 3.13.11
                root: /home/kowshik/Old_G/Semester_2/DL/Assignment_1
                startedAt: "2026-03-03T14:26:32.683533Z"
                writerId: 1huk4rwjfp6yyqov9ehxxvrd6da7btgd
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.11
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
activation:
    value: sigmoid
batch_size:
    value: 64
dataset:
    value: mnist
epochs:
    value: 1
hidden_size:
    value:
        - 64
learning_rate:
    value: 0.01
loss:
    value: cross_entropy
num_layers:
    value: 1
optimizer:
    value: sgd
wandb_project:
    value: dl_1
weight_init:
    value: xavier
