wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
hidden_size:
  value:
  - 32
  - 64
  - 128
learning_rate:
  value: 0.02046234521973622
loss:
  value: cross_entropy
optimizer:
  value: nag
weight_init:
  value: xavier
