wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 5
hidden_layers:
  value: 4
learning_rate:
  value: 0.0007115056213173116
loss:
  value: cross_entropy
num_neurons:
  value: 32
optimizer:
  value: adam
weight_init:
  value: xavier
