wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
dataset:
  value: mnist
epochs:
  value: 10
hidden_layers:
  value: 1
learning_rate:
  value: 0.0002763888820997325
loss:
  value: cross_entropy
num_neurons:
  value: 32
optimizer:
  value: nadam
weight_init:
  value: random
