wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
dataset:
  value: mnist
epochs:
  value: 5
hidden_layers:
  value: 2
learning_rate:
  value: 0.0006054714185760078
loss:
  value: cross_entropy
num_neurons:
  value: 64
optimizer:
  value: adam
weight_init:
  value: xavier
