wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dataset:
  value: mnist
epochs:
  value: 5
hidden_layers:
  value: 1
learning_rate:
  value: 0.005888158215144821
loss:
  value: cross_entropy
num_neurons:
  value: 128
optimizer:
  value: nadam
weight_init:
  value: xavier
