wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_layers:
  value: 3
learning_rate:
  value: 0.000787144897742312
loss:
  value: cross_entropy
num_neurons:
  value: 32
optimizer:
  value: momentum
weight_init:
  value: random
