wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
dataset:
  value: mnist
epochs:
  value: 5
hidden_layers:
  value: 3
learning_rate:
  value: 0.00186275896540459
loss:
  value: cross_entropy
num_neurons:
  value: 128
optimizer:
  value: adam
weight_init:
  value: random
