wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_layers:
  value: 2
learning_rate:
  value: 0.0022461963049620996
loss:
  value: cross_entropy
num_neurons:
  value: 128
optimizer:
  value: adam
weight_init:
  value: xavier
