_wandb:
    value:
        cli_version: 0.25.0
        e:
            tb2twjfatqqdlef4nsuejc1c2gtqc5vi:
                codePath: src\fashion_mnist_transfer.py
                codePathLocal: src\fashion_mnist_transfer.py
                cpu_count: 10
                cpu_count_logical: 16
                disk:
                    /:
                        total: "105853743104"
                        used: "1096409088"
                email: kowshikisme@gmail.com
                executable: C:\Users\deyko\anaconda3\python.exe
                git:
                    commit: 7c1f401865dc249c39e48c9e3d1afa6c313b6b4f
                    remote: https://github.com/ItsKowshik/DA6401_Assignment1.git
                host: ItsKowshik
                memory:
                    total: "16763670528"
                os: Windows-11-10.0.26200-SP0
                program: G:\Semester_2\DL\Assignment_1\src\fashion_mnist_transfer.py
                python: CPython 3.13.5
                root: G:\Semester_2\DL\Assignment_1
                startedAt: "2026-02-26T17:20:00.265756Z"
                writerId: tb2twjfatqqdlef4nsuejc1c2gtqc5vi
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.5
            "5": 0.25.0
            "8":
                - 2
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 64
config_name:
    value: Config_2_Deep_Nadam
dataset:
    value: fashion_mnist
epochs:
    value: 15
hidden_layers:
    value: 3
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
num_neurons:
    value: 128
optimizer:
    value: nadam
weight_init:
    value: xavier
