_wandb:
    value:
        cli_version: 0.25.0
        e:
            szsyuy2q7xsurcass5fk1n4a4x7l1h8s:
                args:
                    - --activation=relu
                    - --batch_size=64
                    - --l1_size=64
                    - --l2_size=32
                    - --l3_size=32
                    - --l4_size=32
                    - --l5_size=64
                    - --l6_size=32
                    - --learning_rate=0.0793658985800366
                    - --loss=cross_entropy
                    - --num_layers=6
                    - --optimizer=sgd
                    - --weight_init=random
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "209715195904"
                        used: "48947281920"
                email: kowshikisme@gmail.com
                executable: C:\Users\deyko\anaconda3\python.exe
                git:
                    commit: 214e59add6c27a1d5c02231baef65658d51ed713
                    remote: https://github.com/ItsKowshik/DA6401_Assignment1.git
                gpu: NVIDIA GeForce RTX 5050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 2560
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5050 Laptop GPU
                      uuid: GPU-f7efdbb2-8b5c-34e0-69c3-d8b8a8e85300
                host: ItsKowshik
                memory:
                    total: "16763629568"
                os: Windows-11-10.0.26200-SP0
                program: E:\Old_G\Semester_2\DL\Assignment_1\src\train.py
                python: CPython 3.13.5
                root: E:\Old_G\Semester_2\DL\Assignment_1
                startedAt: "2026-03-06T04:38:24.648888Z"
                writerId: szsyuy2q7xsurcass5fk1n4a4x7l1h8s
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "3":
                - 2
                - 14
                - 16
            "4": 3.13.5
            "5": 0.25.0
            "8":
                - 2
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
actual_architecture:
    value: '[64, 32, 32, 32, 64, 32]'
batch_size:
    value: 64
dataset:
    value: mnist
epochs:
    value: 15
hidden_size:
    value:
        - 64
        - 32
        - 32
        - 32
        - 64
        - 32
l1_size:
    value: 64
l2_size:
    value: 32
l3_size:
    value: 32
l4_size:
    value: 32
l5_size:
    value: 64
l6_size:
    value: 32
learning_rate:
    value: 0.0793658985800366
loss:
    value: cross_entropy
model_path:
    value: best_model.npy
num_layers:
    value: 6
optimizer:
    value: sgd
wandb_project:
    value: dl_1
weight_decay:
    value: 0
weight_init:
    value: random
