wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dataset:
  value: mnist
epochs:
  value: 10
hidden_layers:
  value: 1
learning_rate:
  value: 0.0014957337802240648
loss:
  value: cross_entropy
num_neurons:
  value: 128
optimizer:
  value: momentum
weight_init:
  value: random
