wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 10
hidden_layers:
  value: 2
learning_rate:
  value: 0.004655855690144401
loss:
  value: cross_entropy
num_neurons:
  value: 32
optimizer:
  value: momentum
weight_init:
  value: xavier
