_wandb:
    value:
        cli_version: 0.25.0
        e:
            vfdy6364d7q5hiz4kgbhwzo3aikgkpya:
                args:
                    - --activation=relu
                    - --batch_size=16
                    - --dataset=mnist
                    - --epochs=5
                    - --hidden_layers=3
                    - --learning_rate=0.0002647687690466543
                    - --loss=cross_entropy
                    - --num_neurons=64
                    - --optimizer=adam
                    - --weight_init=xavier
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "105853743104"
                        used: "1071480832"
                email: kowshikisme@gmail.com
                executable: C:\Users\deyko\anaconda3\python.exe
                git:
                    commit: 7c1f401865dc249c39e48c9e3d1afa6c313b6b4f
                    remote: https://github.com/ItsKowshik/DA6401_Assignment1.git
                gpu: NVIDIA GeForce RTX 5050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 2560
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5050 Laptop GPU
                      uuid: GPU-f7efdbb2-8b5c-34e0-69c3-d8b8a8e85300
                host: ItsKowshik
                memory:
                    total: "16763670528"
                os: Windows-11-10.0.26200-SP0
                program: G:\Semester_2\DL\Assignment_1\src\train.py
                python: CPython 3.13.5
                root: G:\Semester_2\DL\Assignment_1
                startedAt: "2026-02-26T10:52:18.552835Z"
                writerId: vfdy6364d7q5hiz4kgbhwzo3aikgkpya
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
                - 105
            "3":
                - 2
                - 14
                - 16
            "4": 3.13.5
            "5": 0.25.0
            "8":
                - 2
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 16
dataset:
    value: mnist
epochs:
    value: 5
hidden_layers:
    value: 3
learning_rate:
    value: 0.0002647687690466543
loss:
    value: cross_entropy
model_save_path:
    value: best_model.npy
num_neurons:
    value: 64
optimizer:
    value: adam
wandb_project:
    value: da6401-assignment-1
weight_init:
    value: xavier
