wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
hidden_size:
  value: 64
learning_rate:
  value: 0.011803800195813108
loss:
  value: cross_entropy
num_layers:
  value: 1
optimizer:
  value: momentum
weight_init:
  value: random
