wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
hidden_size:
  value: 64
learning_rate:
  value: 0.0005384742896960599
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: rmsprop
weight_init:
  value: xavier
