wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
hidden_size:
  value: 256
learning_rate:
  value: 0.007153317030446865
loss:
  value: mse
num_layers:
  value: 2
optimizer:
  value: nag
weight_init:
  value: random
