wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
hidden_size:
  value: 64
learning_rate:
  value: 0.0013427413870643213
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: momentum
weight_init:
  value: xavier
