wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
hidden_size:
  value:
  - 32
  - 64
  - 64
learning_rate:
  value: 0.0013027630403751945
loss:
  value: mse
optimizer:
  value: nag
weight_init:
  value: random
