wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
hidden_size:
  value:
  - 32
  - 32
  - 32
learning_rate:
  value: 0.020800281525785592
loss:
  value: mse
optimizer:
  value: momentum
weight_init:
  value: xavier
