wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
hidden_size:
  value:
  - 64
  - 32
learning_rate:
  value: 0.0001761985573404414
loss:
  value: cross_entropy
optimizer:
  value: rmsprop
weight_init:
  value: random
