wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
hidden_size:
  value:
  - 32
learning_rate:
  value: 0.0002038581607949347
loss:
  value: mse
optimizer:
  value: momentum
weight_init:
  value: xavier
