wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
hidden_size:
  value:
  - 64
  - 64
  - 64
learning_rate:
  value: 0.02732052694610917
loss:
  value: cross_entropy
optimizer:
  value: momentum
weight_init:
  value: xavier
