wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
hidden_size:
  value:
  - 128
  - 64
  - 128
learning_rate:
  value: 0.0006110461093103658
loss:
  value: mse
optimizer:
  value: nag
weight_init:
  value: xavier
