wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
hidden_size:
  value:
  - 64
  - 128
  - 64
learning_rate:
  value: 0.008031050860725919
loss:
  value: cross_entropy
optimizer:
  value: sgd
weight_init:
  value: random
