wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
hidden_size:
  value:
  - 64
  - 128
  - 128
learning_rate:
  value: 0.0493553485899755
loss:
  value: mse
optimizer:
  value: rmsprop
weight_init:
  value: random
