wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
hidden_size:
  value:
  - 32
  - 32
  - 64
learning_rate:
  value: 0.0003203018351320626
loss:
  value: cross_entropy
optimizer:
  value: nag
weight_init:
  value: random
