wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
hidden_size:
  value:
  - 128
  - 128
  - 64
learning_rate:
  value: 0.04131742958143269
loss:
  value: cross_entropy
optimizer:
  value: sgd
weight_init:
  value: xavier
