wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
hidden_size:
  value:
  - 128
  - 32
  - 128
learning_rate:
  value: 0.0004013938234137473
loss:
  value: cross_entropy
optimizer:
  value: momentum
weight_init:
  value: random
