wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
hidden_size:
  value:
  - 128
  - 128
  - 32
learning_rate:
  value: 0.0002494235749408975
loss:
  value: mse
optimizer:
  value: nag
weight_init:
  value: xavier
