wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
hidden_size:
  value:
  - 64
  - 64
  - 128
learning_rate:
  value: 0.009018428702783313
loss:
  value: mse
optimizer:
  value: sgd
weight_init:
  value: random
