wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
hidden_size:
  value:
  - 128
  - 32
  - 128
learning_rate:
  value: 0.008715057330907569
loss:
  value: cross_entropy
optimizer:
  value: rmsprop
weight_init:
  value: random
