wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
hidden_size:
  value:
  - 64
  - 128
  - 128
learning_rate:
  value: 0.030064897162788363
loss:
  value: cross_entropy
optimizer:
  value: momentum
weight_init:
  value: random
