wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
hidden_size:
  value:
  - 64
  - 128
  - 32
learning_rate:
  value: 0.0021691296568492153
loss:
  value: cross_entropy
optimizer:
  value: sgd
weight_init:
  value: random
