wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
hidden_size:
  value:
  - 64
  - 32
  - 64
learning_rate:
  value: 0.0020482576908174887
loss:
  value: mse
optimizer:
  value: sgd
weight_init:
  value: xavier
