wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
hidden_size:
  value:
  - 64
  - 64
learning_rate:
  value: 0.005664020444622724
loss:
  value: mse
optimizer:
  value: momentum
weight_init:
  value: xavier
