wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
hidden_size:
  value:
  - 64
  - 128
learning_rate:
  value: 0.005590762044154027
loss:
  value: cross_entropy
optimizer:
  value: nag
weight_init:
  value: random
