wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
hidden_size:
  value:
  - 32
  - 128
  - 128
learning_rate:
  value: 0.027456655063642303
loss:
  value: cross_entropy
optimizer:
  value: momentum
weight_init:
  value: xavier
