wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
hidden_size:
  value:
  - 128
  - 64
  - 64
learning_rate:
  value: 0.00017072120787787014
loss:
  value: mse
optimizer:
  value: rmsprop
weight_init:
  value: random
